<?php

namespace Database\Seeders;

use App\Models\Artist;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArtistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        #region Rock - Current / Rising
        Artist::create([
            'name' => 'Black Omen',
            'genre' => 'Rock',
            'bio' => 'A modern heavy rock act known for explosive live energy and rising mainstream appeal.',
            'booking_cost' => 18000.00,
            'guarantee_fee' => 350000.00,
            'popularity' => 82,
            'draw_power' => 80,
            'reliability' => 88,
            'production_value' => 75,
            'fan_loyalty' => 84,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2016-01-01',
        ]);

        Artist::create([
            'name' => 'Silent Oath',
            'genre' => 'Rock',
            'bio' => 'A dark atmospheric rock band with cult momentum and strong festival appeal.',
            'booking_cost' => 22000.00,
            'guarantee_fee' => 500000.00,
            'popularity' => 88,
            'draw_power' => 86,
            'reliability' => 84,
            'production_value' => 82,
            'fan_loyalty' => 92,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '2016-01-01',
        ]);

        Artist::create([
            'name' => 'Golden Vale',
            'genre' => 'Rock',
            'bio' => 'A blues-infused arena-leaning rock band with strong crossover appeal.',
            'booking_cost' => 15000.00,
            'guarantee_fee' => 220000.00,
            'popularity' => 70,
            'draw_power' => 68,
            'reliability' => 90,
            'production_value' => 72,
            'fan_loyalty' => 76,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2012-01-01',
        ]);

        Artist::create([
            'name' => 'Phantom Rite',
            'genre' => 'Rock',
            'bio' => 'A theatrical hard rock act with a polished stage identity and loyal crowd.',
            'booking_cost' => 20000.00,
            'guarantee_fee' => 400000.00,
            'popularity' => 80,
            'draw_power' => 78,
            'reliability' => 87,
            'production_value' => 90,
            'fan_loyalty' => 88,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'Sweden',
            'is_active' => true,
            'career_start_at' => '2008-01-01',
        ]);

        Artist::create([
            'name' => 'Mammoth Ridge',
            'genre' => 'Rock',
            'bio' => 'A riff-driven modern rock act with steady momentum and growing draw.',
            'booking_cost' => 12000.00,
            'guarantee_fee' => 180000.00,
            'popularity' => 66,
            'draw_power' => 65,
            'reliability' => 90,
            'production_value' => 68,
            'fan_loyalty' => 72,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2020-01-01',
        ]);

        Artist::create([
            'name' => 'Dirty Gold',
            'genre' => 'Rock',
            'bio' => 'A gritty throwback rock band with strong club and theater appeal.',
            'booking_cost' => 10000.00,
            'guarantee_fee' => 150000.00,
            'popularity' => 62,
            'draw_power' => 60,
            'reliability' => 85,
            'production_value' => 60,
            'fan_loyalty' => 68,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2017-01-01',
        ]);

        Artist::create([
            'name' => 'Turnstyle',
            'genre' => 'Rock',
            'bio' => 'A boundary-pushing aggressive act with crossover buzz and high-energy crowds.',
            'booking_cost' => 17000.00,
            'guarantee_fee' => 300000.00,
            'popularity' => 84,
            'draw_power' => 82,
            'reliability' => 90,
            'production_value' => 74,
            'fan_loyalty' => 86,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2010-01-01',
        ]);

        Artist::create([
            'name' => 'Spiritshade',
            'genre' => 'Rock',
            'bio' => 'A progressive heavy act blending technical depth with modern mainstream reach.',
            'booking_cost' => 18000.00,
            'guarantee_fee' => 325000.00,
            'popularity' => 83,
            'draw_power' => 80,
            'reliability' => 89,
            'production_value' => 80,
            'fan_loyalty' => 87,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '2017-01-01',
        ]);

        Artist::create([
            'name' => 'Noise Theory',
            'genre' => 'Rock',
            'bio' => 'A modern radio-heavy rock act with strong consistency and touring value.',
            'booking_cost' => 13000.00,
            'guarantee_fee' => 190000.00,
            'popularity' => 68,
            'draw_power' => 66,
            'reliability' => 91,
            'production_value' => 66,
            'fan_loyalty' => 72,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2003-01-01',
        ]);

        Artist::create([
            'name' => 'Jet Horizon',
            'genre' => 'Rock',
            'bio' => 'A dominant modern arena rock act built for massive festival and stadium draw.',
            'booking_cost' => 50000.00,
            'guarantee_fee' => 1200000.00,
            'popularity' => 96,
            'draw_power' => 95,
            'reliability' => 95,
            'production_value' => 94,
            'fan_loyalty' => 95,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1995-01-01',
        ]);
        #endregion

        #region Rock - Veteran / Legacy / Nostalgia
        Artist::create([
            'name' => 'Chrome Riot',
            'genre' => 'Rock',
            'bio' => 'A legendary heavy metal institution with unmatched global recognition.',
            'booking_cost' => 85000.00,
            'guarantee_fee' => 2500000.00,
            'popularity' => 99,
            'draw_power' => 98,
            'reliability' => 92,
            'production_value' => 96,
            'fan_loyalty' => 100,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1981-01-01',
        ]);

        Artist::create([
            'name' => 'Steel Kingdom',
            'genre' => 'Rock',
            'bio' => 'A classic global metal act known for legacy tours and devoted fans.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 2000000.00,
            'popularity' => 96,
            'draw_power' => 94,
            'reliability' => 94,
            'production_value' => 90,
            'fan_loyalty' => 99,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '1975-01-01',
        ]);

        Artist::create([
            'name' => 'Scar Leopard',
            'genre' => 'Rock',
            'bio' => 'A polished veteran rock act known for massive singalong anthems and arena nostalgia.',
            'booking_cost' => 45000.00,
            'guarantee_fee' => 950000.00,
            'popularity' => 86,
            'draw_power' => 84,
            'reliability' => 90,
            'production_value' => 82,
            'fan_loyalty' => 92,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '1977-01-01',
        ]);

        Artist::create([
            'name' => 'Back Alley Saints',
            'genre' => 'Rock',
            'bio' => 'A gritty legacy hard rock band with strong nostalgia value and festival appeal.',
            'booking_cost' => 22000.00,
            'guarantee_fee' => 300000.00,
            'popularity' => 65,
            'draw_power' => 62,
            'reliability' => 80,
            'production_value' => 60,
            'fan_loyalty' => 72,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1986-01-01',
        ]);

        Artist::create([
            'name' => 'Lead Boys',
            'genre' => 'Rock',
            'bio' => 'A flashy veteran glam act with cult nostalgia and smaller-market draw.',
            'booking_cost' => 12000.00,
            'guarantee_fee' => 125000.00,
            'popularity' => 48,
            'draw_power' => 45,
            'reliability' => 72,
            'production_value' => 52,
            'fan_loyalty' => 58,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1988-01-01',
        ]);

        Artist::create([
            'name' => 'Stone Chapel Pilots',
            'genre' => 'Rock',
            'bio' => 'A respected alternative rock legacy act with strong catalog recognition.',
            'booking_cost' => 25000.00,
            'guarantee_fee' => 400000.00,
            'popularity' => 68,
            'draw_power' => 66,
            'reliability' => 78,
            'production_value' => 66,
            'fan_loyalty' => 80,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1989-01-01',
        ]);

        Artist::create([
            'name' => 'Alice in Veins',
            'genre' => 'Rock',
            'bio' => 'A dark iconic grunge-era act with heavy legacy pull and loyal audiences.',
            'booking_cost' => 35000.00,
            'guarantee_fee' => 700000.00,
            'popularity' => 82,
            'draw_power' => 80,
            'reliability' => 76,
            'production_value' => 72,
            'fan_loyalty' => 90,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1987-01-01',
        ]);

        Artist::create([
            'name' => 'Red Fire Peppers',
            'genre' => 'Rock',
            'bio' => 'A globally recognized funk-rock giant built for elite festival and stadium crowds.',
            'booking_cost' => 65000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 97,
            'draw_power' => 95,
            'reliability' => 90,
            'production_value' => 88,
            'fan_loyalty' => 96,
            'requires_full_band' => true,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1983-01-01',
        ]);

        Artist::create([
            'name' => 'Ash Union',
            'genre' => 'Rock',
            'bio' => 'A dependable veteran alt-rock act with steady touring value and nostalgic recognition.',
            'booking_cost' => 18000.00,
            'guarantee_fee' => 250000.00,
            'popularity' => 62,
            'draw_power' => 60,
            'reliability' => 86,
            'production_value' => 58,
            'fan_loyalty' => 70,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '1992-01-01',
        ]);

        Artist::create([
            'name' => 'Wicked Claim',
            'genre' => 'Rock',
            'bio' => 'A classic glam-era act carrying moderate nostalgia and regional booking value.',
            'booking_cost' => 10000.00,
            'guarantee_fee' => 100000.00,
            'popularity' => 42,
            'draw_power' => 40,
            'reliability' => 75,
            'production_value' => 48,
            'fan_loyalty' => 54,
            'requires_full_band' => true,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1985-01-01',
        ]);
        #endregion

        #region Country - Current / Rising
        Artist::create([
            'name' => 'Mason Walker',
            'genre' => 'Country',
            'bio' => 'A dominant modern country headliner with massive mainstream draw and festival value.',
            'booking_cost' => 65000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 96,
            'draw_power' => 95,
            'reliability' => 90,
            'production_value' => 84,
            'fan_loyalty' => 95,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2014-01-01',
        ]);

        Artist::create([
            'name' => 'Zane Bryant',
            'genre' => 'Country',
            'bio' => 'A breakout songwriter-led country act with elite touring momentum.',
            'booking_cost' => 55000.00,
            'guarantee_fee' => 1400000.00,
            'popularity' => 94,
            'draw_power' => 92,
            'reliability' => 88,
            'production_value' => 74,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2019-01-01',
        ]);

        Artist::create([
            'name' => 'Laney Wilder',
            'genre' => 'Country',
            'bio' => 'A polished modern country star with strong crossover growth and loyal crowds.',
            'booking_cost' => 30000.00,
            'guarantee_fee' => 700000.00,
            'popularity' => 84,
            'draw_power' => 82,
            'reliability' => 90,
            'production_value' => 76,
            'fan_loyalty' => 88,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2018-01-01',
        ]);

        Artist::create([
            'name' => 'Brett Zimmerman',
            'genre' => 'Country',
            'bio' => 'A rising modern country act with strong youth appeal and dependable draw.',
            'booking_cost' => 24000.00,
            'guarantee_fee' => 450000.00,
            'popularity' => 80,
            'draw_power' => 78,
            'reliability' => 86,
            'production_value' => 68,
            'fan_loyalty' => 82,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2020-01-01',
        ]);

        Artist::create([
            'name' => 'Jelly Cole',
            'genre' => 'Country',
            'bio' => 'A crossover-heavy country performer with broad mainstream visibility.',
            'booking_cost' => 40000.00,
            'guarantee_fee' => 950000.00,
            'popularity' => 88,
            'draw_power' => 86,
            'reliability' => 84,
            'production_value' => 72,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2011-01-01',
        ]);

        Artist::create([
            'name' => 'Ernie West',
            'genre' => 'Country',
            'bio' => 'A reliable modern country act with steady touring appeal.',
            'booking_cost' => 15000.00,
            'guarantee_fee' => 200000.00,
            'popularity' => 65,
            'draw_power' => 62,
            'reliability' => 90,
            'production_value' => 60,
            'fan_loyalty' => 70,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2016-01-01',
        ]);

        Artist::create([
            'name' => 'Megan Monroe',
            'genre' => 'Country',
            'bio' => 'A fast-rising country act with growing commercial traction.',
            'booking_cost' => 18000.00,
            'guarantee_fee' => 275000.00,
            'popularity' => 74,
            'draw_power' => 72,
            'reliability' => 88,
            'production_value' => 64,
            'fan_loyalty' => 78,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2021-01-01',
        ]);

        Artist::create([
            'name' => 'Cody Jameson',
            'genre' => 'Country',
            'bio' => 'A respected modern country touring act with strong fan loyalty.',
            'booking_cost' => 28000.00,
            'guarantee_fee' => 500000.00,
            'popularity' => 82,
            'draw_power' => 80,
            'reliability' => 92,
            'production_value' => 70,
            'fan_loyalty' => 86,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2015-01-01',
        ]);

        Artist::create([
            'name' => 'Parker Mason',
            'genre' => 'Country',
            'bio' => 'A modern country act with steady regional-to-national growth.',
            'booking_cost' => 19000.00,
            'guarantee_fee' => 300000.00,
            'popularity' => 72,
            'draw_power' => 70,
            'reliability' => 88,
            'production_value' => 62,
            'fan_loyalty' => 76,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2017-01-01',
        ]);

        Artist::create([
            'name' => 'Cole Weston',
            'genre' => 'Country',
            'bio' => 'A rough-edged country-rock leaning act with solid touring consistency.',
            'booking_cost' => 16000.00,
            'guarantee_fee' => 220000.00,
            'popularity' => 66,
            'draw_power' => 64,
            'reliability' => 84,
            'production_value' => 58,
            'fan_loyalty' => 72,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2013-01-01',
        ]);
        #endregion

        #region Country - Veteran / Legacy / Nostalgia
        Artist::create([
            'name' => 'Garth Rivers',
            'genre' => 'Country',
            'bio' => 'A legendary country powerhouse with unmatched nostalgia draw and elite festival value.',
            'booking_cost' => 85000.00,
            'guarantee_fee' => 2200000.00,
            'popularity' => 99,
            'draw_power' => 98,
            'reliability' => 90,
            'production_value' => 88,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1989-01-01',
        ]);

        Artist::create([
            'name' => 'Alan Brooks',
            'genre' => 'Country',
            'bio' => 'A classic country institution with broad generational recognition.',
            'booking_cost' => 40000.00,
            'guarantee_fee' => 850000.00,
            'popularity' => 86,
            'draw_power' => 82,
            'reliability' => 92,
            'production_value' => 70,
            'fan_loyalty' => 92,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1985-01-01',
        ]);

        Artist::create([
            'name' => 'Toby Reed',
            'genre' => 'Country',
            'bio' => 'A patriotic country veteran with strong nostalgia pull and steady touring value.',
            'booking_cost' => 30000.00,
            'guarantee_fee' => 600000.00,
            'popularity' => 78,
            'draw_power' => 76,
            'reliability' => 86,
            'production_value' => 68,
            'fan_loyalty' => 84,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1993-01-01',
        ]);

        Artist::create([
            'name' => 'Keith Urbane',
            'genre' => 'Country',
            'bio' => 'A polished crossover veteran with international recognition and strong reliability.',
            'booking_cost' => 50000.00,
            'guarantee_fee' => 1100000.00,
            'popularity' => 90,
            'draw_power' => 88,
            'reliability' => 94,
            'production_value' => 82,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Australia',
            'is_active' => true,
            'career_start_at' => '1991-01-01',
        ]);

        Artist::create([
            'name' => 'Brad Grace',
            'genre' => 'Country',
            'bio' => 'A dependable legacy country act with strong emotional catalog appeal.',
            'booking_cost' => 22000.00,
            'guarantee_fee' => 350000.00,
            'popularity' => 68,
            'draw_power' => 65,
            'reliability' => 88,
            'production_value' => 60,
            'fan_loyalty' => 76,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1998-01-01',
        ]);

        Artist::create([
            'name' => 'Tim McCall',
            'genre' => 'Country',
            'bio' => 'A veteran mainstream country performer with strong recognition and stable bookings.',
            'booking_cost' => 26000.00,
            'guarantee_fee' => 450000.00,
            'popularity' => 72,
            'draw_power' => 70,
            'reliability' => 90,
            'production_value' => 64,
            'fan_loyalty' => 80,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1994-01-01',
        ]);

        Artist::create([
            'name' => 'George Straiton',
            'genre' => 'Country',
            'bio' => 'A near-mythic country icon with enormous prestige and elite nostalgia demand.',
            'booking_cost' => 95000.00,
            'guarantee_fee' => 2500000.00,
            'popularity' => 100,
            'draw_power' => 98,
            'reliability' => 96,
            'production_value' => 82,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1981-01-01',
        ]);

        Artist::create([
            'name' => 'Ronnie Dunnley',
            'genre' => 'Country',
            'bio' => 'A classic country voice with reliable nostalgia value and veteran touring appeal.',
            'booking_cost' => 18000.00,
            'guarantee_fee' => 250000.00,
            'popularity' => 60,
            'draw_power' => 58,
            'reliability' => 88,
            'production_value' => 54,
            'fan_loyalty' => 72,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1990-01-01',
        ]);

        Artist::create([
            'name' => 'Clint Blackwell',
            'genre' => 'Country',
            'bio' => 'A respected traditional country veteran with loyal audiences and steady booking value.',
            'booking_cost' => 15000.00,
            'guarantee_fee' => 200000.00,
            'popularity' => 55,
            'draw_power' => 52,
            'reliability' => 90,
            'production_value' => 50,
            'fan_loyalty' => 68,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1987-01-01',
        ]);

        Artist::create([
            'name' => 'Shania Twaines',
            'genre' => 'Country',
            'bio' => 'A crossover global superstar with enormous legacy draw and festival prestige.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 97,
            'draw_power' => 94,
            'reliability' => 90,
            'production_value' => 86,
            'fan_loyalty' => 96,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '1993-01-01',
        ]);
        #endregion

        #region Pop - Current / Rising
        Artist::create([
            'name' => 'Taylor Swifton',
            'genre' => 'Pop',
            'bio' => 'A generational global superstar with elite draw power and unmatched fan loyalty.',
            'booking_cost' => 120000.00,
            'guarantee_fee' => 4000000.00,
            'popularity' => 100,
            'draw_power' => 100,
            'reliability' => 96,
            'production_value' => 98,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2006-01-01',
        ]);

        Artist::create([
            'name' => 'Harry Stylz',
            'genre' => 'Pop',
            'bio' => 'A massive crossover pop act with global festival and arena appeal.',
            'booking_cost' => 85000.00,
            'guarantee_fee' => 2500000.00,
            'popularity' => 97,
            'draw_power' => 95,
            'reliability' => 92,
            'production_value' => 90,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '2010-01-01',
        ]);

        Artist::create([
            'name' => 'Dua Lipae',
            'genre' => 'Pop',
            'bio' => 'A polished international pop star built for major festival stages.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 94,
            'draw_power' => 92,
            'reliability' => 93,
            'production_value' => 94,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '2015-01-01',
        ]);

        Artist::create([
            'name' => 'Olivia Rodri',
            'genre' => 'Pop',
            'bio' => 'A young powerhouse pop act with explosive mainstream growth.',
            'booking_cost' => 55000.00,
            'guarantee_fee' => 1300000.00,
            'popularity' => 90,
            'draw_power' => 88,
            'reliability' => 90,
            'production_value' => 84,
            'fan_loyalty' => 92,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2020-01-01',
        ]);

        Artist::create([
            'name' => 'Bruno Marsen',
            'genre' => 'Pop',
            'bio' => 'A premium live performer with exceptional crossover and festival value.',
            'booking_cost' => 90000.00,
            'guarantee_fee' => 3000000.00,
            'popularity' => 98,
            'draw_power' => 96,
            'reliability' => 95,
            'production_value' => 98,
            'fan_loyalty' => 95,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2010-01-01',
        ]);

        Artist::create([
            'name' => 'Billie Eilishen',
            'genre' => 'Pop',
            'bio' => 'A modern alternative-pop giant with deep fan loyalty and elite cultural relevance.',
            'booking_cost' => 65000.00,
            'guarantee_fee' => 1700000.00,
            'popularity' => 93,
            'draw_power' => 90,
            'reliability' => 92,
            'production_value' => 88,
            'fan_loyalty' => 96,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2017-01-01',
        ]);

        Artist::create([
            'name' => 'Weeknd Black',
            'genre' => 'Pop',
            'bio' => 'A global pop-R&B titan with huge production expectations and top-tier draw.',
            'booking_cost' => 100000.00,
            'guarantee_fee' => 3200000.00,
            'popularity' => 99,
            'draw_power' => 98,
            'reliability' => 94,
            'production_value' => 98,
            'fan_loyalty' => 96,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '2011-01-01',
        ]);

        Artist::create([
            'name' => 'Ariana Grandis',
            'genre' => 'Pop',
            'bio' => 'A dominant global pop act with elite vocal prestige and huge fan loyalty.',
            'booking_cost' => 85000.00,
            'guarantee_fee' => 2400000.00,
            'popularity' => 97,
            'draw_power' => 95,
            'reliability' => 91,
            'production_value' => 92,
            'fan_loyalty' => 98,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2013-01-01',
        ]);

        Artist::create([
            'name' => 'Post Malonez',
            'genre' => 'Pop',
            'bio' => 'A genre-blending arena-level act with broad mainstream booking power.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 1900000.00,
            'popularity' => 94,
            'draw_power' => 92,
            'reliability' => 90,
            'production_value' => 84,
            'fan_loyalty' => 92,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2015-01-01',
        ]);

        Artist::create([
            'name' => 'Justin Beibern',
            'genre' => 'Pop',
            'bio' => 'A long-running global pop star with strong nostalgia and active draw.',
            'booking_cost' => 80000.00,
            'guarantee_fee' => 2200000.00,
            'popularity' => 95,
            'draw_power' => 93,
            'reliability' => 86,
            'production_value' => 88,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '2009-01-01',
        ]);
        #endregion

        #region Pop - Veteran / Legacy / Nostalgia
        Artist::create([
            'name' => 'Michael Jaxon',
            'genre' => 'Pop',
            'bio' => 'A legendary pop icon whose catalog still drives unmatched nostalgia and prestige.',
            'booking_cost' => 150000.00,
            'guarantee_fee' => 5000000.00,
            'popularity' => 100,
            'draw_power' => 100,
            'reliability' => 95,
            'production_value' => 100,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => false,
            'career_start_at' => '1971-01-01',
            'retired_at' => '2009-06-25',
        ]);

        Artist::create([
            'name' => 'Madonner',
            'genre' => 'Pop',
            'bio' => 'A defining global pop figure with elite longevity and major festival prestige.',
            'booking_cost' => 95000.00,
            'guarantee_fee' => 2500000.00,
            'popularity' => 98,
            'draw_power' => 95,
            'reliability' => 90,
            'production_value' => 96,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1983-01-01',
        ]);

        Artist::create([
            'name' => 'Prince Royale',
            'genre' => 'Pop',
            'bio' => 'A genre-defining icon with immense artistic prestige and legacy pull.',
            'booking_cost' => 120000.00,
            'guarantee_fee' => 4000000.00,
            'popularity' => 100,
            'draw_power' => 98,
            'reliability' => 94,
            'production_value' => 100,
            'fan_loyalty' => 98,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => false,
            'career_start_at' => '1978-01-01',
            'retired_at' => '2016-04-21',
        ]);

        Artist::create([
            'name' => 'Whitney Housten',
            'genre' => 'Pop',
            'bio' => 'A legendary vocal powerhouse whose legacy remains globally recognized.',
            'booking_cost' => 100000.00,
            'guarantee_fee' => 3000000.00,
            'popularity' => 99,
            'draw_power' => 96,
            'reliability' => 90,
            'production_value' => 98,
            'fan_loyalty' => 96,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => false,
            'career_start_at' => '1985-01-01',
            'retired_at' => '2012-02-11',
        ]);

        Artist::create([
            'name' => 'George Michaelsen',
            'genre' => 'Pop',
            'bio' => 'A beloved legacy pop figure with strong nostalgia and catalog recognition.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 90,
            'draw_power' => 86,
            'reliability' => 88,
            'production_value' => 84,
            'fan_loyalty' => 88,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'UK',
            'is_active' => false,
            'career_start_at' => '1984-01-01',
            'retired_at' => '2016-12-25',
        ]);

        Artist::create([
            'name' => 'Janet Jax',
            'genre' => 'Pop',
            'bio' => 'A major legacy pop performer with strong stage prestige and veteran draw.',
            'booking_cost' => 45000.00,
            'guarantee_fee' => 900000.00,
            'popularity' => 82,
            'draw_power' => 80,
            'reliability' => 90,
            'production_value' => 90,
            'fan_loyalty' => 86,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1986-01-01',
        ]);

        Artist::create([
            'name' => 'Cyndi Laupern',
            'genre' => 'Pop',
            'bio' => 'A classic pop icon with strong nostalgia value and recognizable global appeal.',
            'booking_cost' => 25000.00,
            'guarantee_fee' => 400000.00,
            'popularity' => 68,
            'draw_power' => 64,
            'reliability' => 92,
            'production_value' => 68,
            'fan_loyalty' => 74,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1983-01-01',
        ]);

        Artist::create([
            'name' => 'Phil Collen',
            'genre' => 'Pop',
            'bio' => 'A respected veteran crossover performer with enduring recognition.',
            'booking_cost' => 30000.00,
            'guarantee_fee' => 500000.00,
            'popularity' => 74,
            'draw_power' => 70,
            'reliability' => 94,
            'production_value' => 70,
            'fan_loyalty' => 78,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'UK',
            'is_active' => true,
            'career_start_at' => '1981-01-01',
        ]);

        Artist::create([
            'name' => 'Lionel Ritchiex',
            'genre' => 'Pop',
            'bio' => 'A legendary crossover act with dependable nostalgia and premium event value.',
            'booking_cost' => 50000.00,
            'guarantee_fee' => 1000000.00,
            'popularity' => 84,
            'draw_power' => 80,
            'reliability' => 95,
            'production_value' => 74,
            'fan_loyalty' => 86,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '1982-01-01',
        ]);

        Artist::create([
            'name' => 'Tina Turnor',
            'genre' => 'Pop',
            'bio' => 'A powerhouse legacy icon with immense stage prestige and lasting fan recognition.',
            'booking_cost' => 90000.00,
            'guarantee_fee' => 2200000.00,
            'popularity' => 95,
            'draw_power' => 90,
            'reliability' => 94,
            'production_value' => 96,
            'fan_loyalty' => 92,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Switzerland',
            'is_active' => false,
            'career_start_at' => '1974-01-01',
            'retired_at' => '2023-05-24',
        ]);
        #endregion

        #region EDM - Current / Rising
        Artist::create([
            'name' => 'Jack Summit',
            'genre' => 'EDM',
            'bio' => 'A dominant festival-focused house act with elite modern momentum and crowd pull.',
            'booking_cost' => 55000.00,
            'guarantee_fee' => 1400000.00,
            'popularity' => 92,
            'draw_power' => 90,
            'reliability' => 90,
            'production_value' => 94,
            'fan_loyalty' => 88,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2018-01-01',
        ]);

        Artist::create([
            'name' => 'DeadWolf',
            'genre' => 'EDM',
            'bio' => 'A masked global electronic act built for major production-heavy stages.',
            'booking_cost' => 80000.00,
            'guarantee_fee' => 2400000.00,
            'popularity' => 96,
            'draw_power' => 95,
            'reliability' => 92,
            'production_value' => 100,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '2009-01-01',
        ]);

        Artist::create([
            'name' => 'Martin Garrox',
            'genre' => 'EDM',
            'bio' => 'A polished global festival headliner with strong crossover appeal.',
            'booking_cost' => 65000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 94,
            'draw_power' => 92,
            'reliability' => 94,
            'production_value' => 96,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Netherlands',
            'is_active' => true,
            'career_start_at' => '2013-01-01',
        ]);

        Artist::create([
            'name' => 'Zed',
            'genre' => 'EDM',
            'bio' => 'A crossover electronic producer with premium stage polish and mainstream value.',
            'booking_cost' => 45000.00,
            'guarantee_fee' => 1000000.00,
            'popularity' => 86,
            'draw_power' => 84,
            'reliability' => 95,
            'production_value' => 92,
            'fan_loyalty' => 84,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Germany',
            'is_active' => true,
            'career_start_at' => '2012-01-01',
        ]);

        Artist::create([
            'name' => 'Kygoe',
            'genre' => 'EDM',
            'bio' => 'A melodic global electronic act with strong mainstream and destination festival appeal.',
            'booking_cost' => 50000.00,
            'guarantee_fee' => 1200000.00,
            'popularity' => 88,
            'draw_power' => 86,
            'reliability' => 94,
            'production_value' => 90,
            'fan_loyalty' => 86,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Norway',
            'is_active' => true,
            'career_start_at' => '2014-01-01',
        ]);

        Artist::create([
            'name' => 'Illeniumx',
            'genre' => 'EDM',
            'bio' => 'A melodic bass-focused act with strong loyalty and premium festival relevance.',
            'booking_cost' => 42000.00,
            'guarantee_fee' => 900000.00,
            'popularity' => 84,
            'draw_power' => 82,
            'reliability' => 92,
            'production_value' => 90,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2015-01-01',
        ]);

        Artist::create([
            'name' => 'Alessoq',
            'genre' => 'EDM',
            'bio' => 'A veteran-leaning modern EDM act with strong production-heavy festival draw.',
            'booking_cost' => 40000.00,
            'guarantee_fee' => 850000.00,
            'popularity' => 82,
            'draw_power' => 80,
            'reliability' => 94,
            'production_value' => 88,
            'fan_loyalty' => 82,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Sweden',
            'is_active' => true,
            'career_start_at' => '2011-01-01',
        ]);

        Artist::create([
            'name' => 'Rezzor',
            'genre' => 'EDM',
            'bio' => 'A dark electronic act with distinct branding and strong niche loyalty.',
            'booking_cost' => 28000.00,
            'guarantee_fee' => 500000.00,
            'popularity' => 72,
            'draw_power' => 70,
            'reliability' => 92,
            'production_value' => 86,
            'fan_loyalty' => 82,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'Canada',
            'is_active' => true,
            'career_start_at' => '2016-01-01',
        ]);

        Artist::create([
            'name' => 'Porter Robins',
            'genre' => 'EDM',
            'bio' => 'A respected electronic visionary with premium artistic and festival prestige.',
            'booking_cost' => 35000.00,
            'guarantee_fee' => 650000.00,
            'popularity' => 76,
            'draw_power' => 74,
            'reliability' => 94,
            'production_value' => 92,
            'fan_loyalty' => 88,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2011-01-01',
        ]);

        Artist::create([
            'name' => 'Fisherz',
            'genre' => 'EDM',
            'bio' => 'A high-energy dance act with major club-to-festival crossover strength.',
            'booking_cost' => 38000.00,
            'guarantee_fee' => 700000.00,
            'popularity' => 80,
            'draw_power' => 78,
            'reliability' => 92,
            'production_value' => 84,
            'fan_loyalty' => 80,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'Australia',
            'is_active' => true,
            'career_start_at' => '2017-01-01',
        ]);
        #endregion

        #region EDM - Veteran / Legacy / Nostalgia
        Artist::create([
            'name' => 'Tiestro',
            'genre' => 'EDM',
            'bio' => 'A legendary global EDM icon with elite festival prestige and long-running draw.',
            'booking_cost' => 90000.00,
            'guarantee_fee' => 2800000.00,
            'popularity' => 98,
            'draw_power' => 96,
            'reliability' => 95,
            'production_value' => 98,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Netherlands',
            'is_active' => true,
            'career_start_at' => '1997-01-01',
        ]);

        Artist::create([
            'name' => 'Armon Van Buuren',
            'genre' => 'EDM',
            'bio' => 'A trance institution with premium longevity and global festival recognition.',
            'booking_cost' => 70000.00,
            'guarantee_fee' => 1800000.00,
            'popularity' => 90,
            'draw_power' => 88,
            'reliability' => 96,
            'production_value' => 94,
            'fan_loyalty' => 92,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Netherlands',
            'is_active' => true,
            'career_start_at' => '2001-01-01',
        ]);

        Artist::create([
            'name' => 'Calvin Harrik',
            'genre' => 'EDM',
            'bio' => 'A crossover dance titan with huge mainstream recognition and premium draw.',
            'booking_cost' => 95000.00,
            'guarantee_fee' => 3000000.00,
            'popularity' => 99,
            'draw_power' => 97,
            'reliability' => 95,
            'production_value' => 96,
            'fan_loyalty' => 94,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Scotland',
            'is_active' => true,
            'career_start_at' => '2007-01-01',
        ]);

        Artist::create([
            'name' => 'Skrillix',
            'genre' => 'EDM',
            'bio' => 'A highly influential electronic producer with deep fan loyalty and elite festival value.',
            'booking_cost' => 80000.00,
            'guarantee_fee' => 2200000.00,
            'popularity' => 95,
            'draw_power' => 92,
            'reliability' => 94,
            'production_value' => 98,
            'fan_loyalty' => 96,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2010-01-01',
        ]);

        Artist::create([
            'name' => 'David Guetts',
            'genre' => 'EDM',
            'bio' => 'A veteran global EDM headliner with strong crossover and festival power.',
            'booking_cost' => 85000.00,
            'guarantee_fee' => 2400000.00,
            'popularity' => 96,
            'draw_power' => 94,
            'reliability' => 95,
            'production_value' => 94,
            'fan_loyalty' => 90,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'France',
            'is_active' => true,
            'career_start_at' => '2002-01-01',
        ]);

        Artist::create([
            'name' => 'Steve Aokix',
            'genre' => 'EDM',
            'bio' => 'A high-energy electronic veteran known for spectacle-heavy live shows.',
            'booking_cost' => 50000.00,
            'guarantee_fee' => 1200000.00,
            'popularity' => 84,
            'draw_power' => 82,
            'reliability' => 92,
            'production_value' => 92,
            'fan_loyalty' => 84,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2005-01-01',
        ]);

        Artist::create([
            'name' => 'Diplox',
            'genre' => 'EDM',
            'bio' => 'A globally recognized crossover EDM act with major cultural relevance.',
            'booking_cost' => 65000.00,
            'guarantee_fee' => 1600000.00,
            'popularity' => 88,
            'draw_power' => 86,
            'reliability' => 88,
            'production_value' => 90,
            'fan_loyalty' => 86,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2004-01-01',
        ]);

        Artist::create([
            'name' => 'Kaskadex',
            'genre' => 'EDM',
            'bio' => 'A respected progressive electronic act with veteran prestige and dependable draw.',
            'booking_cost' => 35000.00,
            'guarantee_fee' => 700000.00,
            'popularity' => 74,
            'draw_power' => 72,
            'reliability' => 95,
            'production_value' => 86,
            'fan_loyalty' => 80,
            'requires_full_band' => false,
            'requires_large_stage' => false,
            'based_in' => 'USA',
            'is_active' => true,
            'career_start_at' => '2001-01-01',
        ]);

        Artist::create([
            'name' => 'Avicci',
            'genre' => 'EDM',
            'bio' => 'A legendary melodic EDM figure whose influence remains massive across generations.',
            'booking_cost' => 100000.00,
            'guarantee_fee' => 3200000.00,
            'popularity' => 100,
            'draw_power' => 98,
            'reliability' => 96,
            'production_value' => 98,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'Sweden',
            'is_active' => false,
            'career_start_at' => '2008-01-01',
            'retired_at' => '2018-04-20',
        ]);

        Artist::create([
            'name' => 'Daft Future',
            'genre' => 'EDM',
            'bio' => 'A legendary electronic duo with unmatched prestige and enormous legacy draw.',
            'booking_cost' => 120000.00,
            'guarantee_fee' => 4000000.00,
            'popularity' => 100,
            'draw_power' => 99,
            'reliability' => 94,
            'production_value' => 100,
            'fan_loyalty' => 100,
            'requires_full_band' => false,
            'requires_large_stage' => true,
            'based_in' => 'France',
            'is_active' => false,
            'career_start_at' => '1993-01-01',
            'retired_at' => '2021-02-22',
        ]);
        #endregion
    }
}
