<?php

namespace Database\Seeders;

use App\Models\Venue;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VenueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        #region Chicago, IL
        Venue::create([
            'name' => 'Great Lakes Stadium',
            'city' => 'Chicago',
            'state' => 'IL',
            'country' => 'USA',
            'type' => 'stadium',
            'tier' => 'stadium',
            'capacity' => 58000,
            'rental_cost' => 350000.00,
            'maintenance_cost' => 75000.00,
            'weather_exposure' => 60,
            'prestige' => 85,
            'parking_rating' => 90,
            'max_stages' => 2,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A major Chicago sports venue built for large-scale stadium events.',
        ]);

        Venue::create([
            'name' => 'Wind City Arena',
            'city' => 'Chicago',
            'state' => 'IL',
            'country' => 'USA',
            'type' => 'arena',
            'tier' => 'arena',
            'capacity' => 19000,
            'rental_cost' => 140000.00,
            'maintenance_cost' => 30000.00,
            'weather_exposure' => 5,
            'prestige' => 72,
            'parking_rating' => 78,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A high-capacity indoor arena suited for major tours and premium concerts.',
        ]);

        Venue::create([
            'name' => 'Grant Park Pavilion',
            'city' => 'Chicago',
            'state' => 'IL',
            'country' => 'USA',
            'type' => 'pavilion',
            'tier' => 'festival',
            'capacity' => 14000,
            'rental_cost' => 100000.00,
            'maintenance_cost' => 20000.00,
            'weather_exposure' => 100,
            'prestige' => 68,
            'parking_rating' => 65,
            'max_stages' => 4,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A flexible outdoor event space ideal for festival layouts and seasonal events.',
        ]);

        Venue::create([
            'name' => 'North Shore Theater',
            'city' => 'Chicago',
            'state' => 'IL',
            'country' => 'USA',
            'type' => 'theater',
            'tier' => 'hall',
            'capacity' => 4200,
            'rental_cost' => 45000.00,
            'maintenance_cost' => 9000.00,
            'weather_exposure' => 0,
            'prestige' => 55,
            'parking_rating' => 50,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A mid-sized indoor theater built for intimate performances and specialty events.',
        ]);

        Venue::create([
            'name' => 'Sublevel Club',
            'city' => 'Chicago',
            'state' => 'IL',
            'country' => 'USA',
            'type' => 'club',
            'tier' => 'club',
            'capacity' => 1300,
            'rental_cost' => 12000.00,
            'maintenance_cost' => 3000.00,
            'weather_exposure' => 0,
            'prestige' => 35,
            'parking_rating' => 30,
            'max_stages' => 1,
            'curfew_hour' => 1,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A gritty underground venue focused on emerging acts and smaller live events.',
        ]);
        #endregion

        #region Los Angeles, CA
        Venue::create([
            'name' => 'Pacific Crown Stadium',
            'city' => 'Los Angeles',
            'state' => 'CA',
            'country' => 'USA',
            'type' => 'stadium',
            'tier' => 'stadium',
            'capacity' => 72000,
            'rental_cost' => 450000.00,
            'maintenance_cost' => 95000.00,
            'weather_exposure' => 65,
            'prestige' => 95,
            'parking_rating' => 88,
            'max_stages' => 2,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A premier west coast stadium built for elite-scale events and global tours.',
        ]);

        Venue::create([
            'name' => 'Sunset Arena',
            'city' => 'Los Angeles',
            'state' => 'CA',
            'country' => 'USA',
            'type' => 'arena',
            'tier' => 'arena',
            'capacity' => 20500,
            'rental_cost' => 155000.00,
            'maintenance_cost' => 32000.00,
            'weather_exposure' => 5,
            'prestige' => 80,
            'parking_rating' => 75,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A polished indoor arena known for national acts and televised events.',
        ]);

        Venue::create([
            'name' => 'Hollywood Bowl Park',
            'city' => 'Los Angeles',
            'state' => 'CA',
            'country' => 'USA',
            'type' => 'park',
            'tier' => 'festival',
            'capacity' => 15000,
            'rental_cost' => 115000.00,
            'maintenance_cost' => 22000.00,
            'weather_exposure' => 100,
            'prestige' => 78,
            'parking_rating' => 70,
            'max_stages' => 4,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A scenic open-air event park designed for large festival gatherings.',
        ]);

        Venue::create([
            'name' => 'Echo District Hall',
            'city' => 'Los Angeles',
            'state' => 'CA',
            'country' => 'USA',
            'type' => 'hall',
            'tier' => 'hall',
            'capacity' => 3800,
            'rental_cost' => 42000.00,
            'maintenance_cost' => 8500.00,
            'weather_exposure' => 0,
            'prestige' => 52,
            'parking_rating' => 45,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A versatile indoor hall suited for mid-tier touring acts and showcases.',
        ]);

        Venue::create([
            'name' => 'Neon Room',
            'city' => 'Los Angeles',
            'state' => 'CA',
            'country' => 'USA',
            'type' => 'club',
            'tier' => 'club',
            'capacity' => 1100,
            'rental_cost' => 15000.00,
            'maintenance_cost' => 3500.00,
            'weather_exposure' => 0,
            'prestige' => 40,
            'parking_rating' => 25,
            'max_stages' => 1,
            'curfew_hour' => 1,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A compact nightlife venue known for smaller performances and breakout acts.',
        ]);
        #endregion

        #region Dallas, TX
        Venue::create([
            'name' => 'Lone Star Stadium',
            'city' => 'Dallas',
            'state' => 'TX',
            'country' => 'USA',
            'type' => 'stadium',
            'tier' => 'stadium',
            'capacity' => 67000,
            'rental_cost' => 400000.00,
            'maintenance_cost' => 85000.00,
            'weather_exposure' => 60,
            'prestige' => 88,
            'parking_rating' => 92,
            'max_stages' => 2,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A massive Texas sports venue built for premium concerts and flagship events.',
        ]);

        Venue::create([
            'name' => 'Metroplex Arena',
            'city' => 'Dallas',
            'state' => 'TX',
            'country' => 'USA',
            'type' => 'arena',
            'tier' => 'arena',
            'capacity' => 18000,
            'rental_cost' => 135000.00,
            'maintenance_cost' => 28000.00,
            'weather_exposure' => 5,
            'prestige' => 68,
            'parking_rating' => 80,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A dependable indoor arena suited for major touring packages and large live shows.',
        ]);

        Venue::create([
            'name' => 'State Fair Pavilion',
            'city' => 'Dallas',
            'state' => 'TX',
            'country' => 'USA',
            'type' => 'fairgrounds',
            'tier' => 'festival',
            'capacity' => 13500,
            'rental_cost' => 95000.00,
            'maintenance_cost' => 20000.00,
            'weather_exposure' => 100,
            'prestige' => 62,
            'parking_rating' => 88,
            'max_stages' => 4,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A broad fairgrounds venue built for flexible outdoor festivals and seasonal events.',
        ]);

        Venue::create([
            'name' => 'Deep South Hall',
            'city' => 'Dallas',
            'state' => 'TX',
            'country' => 'USA',
            'type' => 'hall',
            'tier' => 'hall',
            'capacity' => 2900,
            'rental_cost' => 32000.00,
            'maintenance_cost' => 7000.00,
            'weather_exposure' => 0,
            'prestige' => 45,
            'parking_rating' => 55,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A regional indoor hall favored for smaller concerts, showcases, and touring stops.',
        ]);

        Venue::create([
            'name' => 'Rail Yard Club',
            'city' => 'Dallas',
            'state' => 'TX',
            'country' => 'USA',
            'type' => 'club',
            'tier' => 'club',
            'capacity' => 900,
            'rental_cost' => 10000.00,
            'maintenance_cost' => 2500.00,
            'weather_exposure' => 0,
            'prestige' => 28,
            'parking_rating' => 35,
            'max_stages' => 1,
            'curfew_hour' => 1,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A compact industrial-style venue built for grassroots acts and intimate crowds.',
        ]);
        #endregion

        #region New York City, NY
        Venue::create([
            'name' => 'Empire Field',
            'city' => 'New York City',
            'state' => 'NY',
            'country' => 'USA',
            'type' => 'field',
            'tier' => 'stadium',
            'capacity' => 61000,
            'rental_cost' => 425000.00,
            'maintenance_cost' => 90000.00,
            'weather_exposure' => 65,
            'prestige' => 92,
            'parking_rating' => 78,
            'max_stages' => 2,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A premier east coast sports field regularly used for large-scale live entertainment.',
        ]);

        Venue::create([
            'name' => 'Hudson Arena',
            'city' => 'New York City',
            'state' => 'NY',
            'country' => 'USA',
            'type' => 'arena',
            'tier' => 'arena',
            'capacity' => 19500,
            'rental_cost' => 165000.00,
            'maintenance_cost' => 34000.00,
            'weather_exposure' => 5,
            'prestige' => 82,
            'parking_rating' => 60,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A high-demand urban arena built for elite touring acts and televised events.',
        ]);

        Venue::create([
            'name' => 'Brookline Pavilion',
            'city' => 'New York City',
            'state' => 'NY',
            'country' => 'USA',
            'type' => 'pavilion',
            'tier' => 'festival',
            'capacity' => 12000,
            'rental_cost' => 110000.00,
            'maintenance_cost' => 22000.00,
            'weather_exposure' => 100,
            'prestige' => 70,
            'parking_rating' => 50,
            'max_stages' => 4,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A versatile outdoor pavilion used for large events and festival-style setups.',
        ]);

        Venue::create([
            'name' => 'Grand Hall Theater',
            'city' => 'New York City',
            'state' => 'NY',
            'country' => 'USA',
            'type' => 'theater',
            'tier' => 'hall',
            'capacity' => 4500,
            'rental_cost' => 52000.00,
            'maintenance_cost' => 10000.00,
            'weather_exposure' => 0,
            'prestige' => 65,
            'parking_rating' => 40,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A refined indoor theater built for specialty performances and mid-tier touring acts.',
        ]);

        Venue::create([
            'name' => 'Lower District Club',
            'city' => 'New York City',
            'state' => 'NY',
            'country' => 'USA',
            'type' => 'club',
            'tier' => 'club',
            'capacity' => 1400,
            'rental_cost' => 18000.00,
            'maintenance_cost' => 4000.00,
            'weather_exposure' => 0,
            'prestige' => 42,
            'parking_rating' => 20,
            'max_stages' => 1,
            'curfew_hour' => 2,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A dense city club popular for late-night events and rising performers.',
        ]);
        #endregion

        #region Atlanta, GA
        Venue::create([
            'name' => 'Peachtree Field',
            'city' => 'Atlanta',
            'state' => 'GA',
            'country' => 'USA',
            'type' => 'field',
            'tier' => 'stadium',
            'capacity' => 53000,
            'rental_cost' => 325000.00,
            'maintenance_cost' => 70000.00,
            'weather_exposure' => 60,
            'prestige' => 80,
            'parking_rating' => 88,
            'max_stages' => 2,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A large southern sports venue built for major outdoor events and touring productions.',
        ]);

        Venue::create([
            'name' => 'Southern Arena',
            'city' => 'Atlanta',
            'state' => 'GA',
            'country' => 'USA',
            'type' => 'arena',
            'tier' => 'arena',
            'capacity' => 16500,
            'rental_cost' => 120000.00,
            'maintenance_cost' => 26000.00,
            'weather_exposure' => 5,
            'prestige' => 64,
            'parking_rating' => 74,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => false,
            'is_active' => true,
            'bio' => 'A reliable indoor arena designed for regional and national touring events.',
        ]);

        Venue::create([
            'name' => 'Centennial Park Grounds',
            'city' => 'Atlanta',
            'state' => 'GA',
            'country' => 'USA',
            'type' => 'grounds',
            'tier' => 'festival',
            'capacity' => 11000,
            'rental_cost' => 90000.00,
            'maintenance_cost' => 18000.00,
            'weather_exposure' => 100,
            'prestige' => 66,
            'parking_rating' => 72,
            'max_stages' => 5,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A large open festival grounds built for multi-stage outdoor events and destination weekends.',
        ]);

        Venue::create([
            'name' => 'Midtown Hall',
            'city' => 'Atlanta',
            'state' => 'GA',
            'country' => 'USA',
            'type' => 'hall',
            'tier' => 'hall',
            'capacity' => 2700,
            'rental_cost' => 30000.00,
            'maintenance_cost' => 6500.00,
            'weather_exposure' => 0,
            'prestige' => 44,
            'parking_rating' => 48,
            'max_stages' => 1,
            'curfew_hour' => 23,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A practical mid-sized hall built for local circuits and developing tours.',
        ]);

        Venue::create([
            'name' => 'Red Clay Room',
            'city' => 'Atlanta',
            'state' => 'GA',
            'country' => 'USA',
            'type' => 'club',
            'tier' => 'club',
            'capacity' => 850,
            'rental_cost' => 9500.00,
            'maintenance_cost' => 2200.00,
            'weather_exposure' => 0,
            'prestige' => 25,
            'parking_rating' => 30,
            'max_stages' => 1,
            'curfew_hour' => 1,
            'noise_restriction' => true,
            'is_active' => true,
            'bio' => 'A small gritty live room built for grassroots acts and underground shows.',
        ]);
        #endregion
    }
}
